### ISSUE TITLE
what rules does python-format process follow?

### ISSUE THREAD

**Issue by zheyuanWang** [jbockle/format-files#39]
I didn't see any rule-settings in the extension. 

Is there a dependency for it, that config the rules?

**Comment by jbockle** [comment]
hi @zheyuanWang, this extension doesn't specify any language specific rules-instead it uses formatters installed in your vscode to format, you can customize python formatting rules with your preferred vscode python formatter.  this extension only provides a way to apply formatters to multiple files instead of having to manually open each file one-by-one to run formatting operations.
