### ISSUE TITLE
Memory Leak in combination with MS C++ Plugin

### ISSUE THREAD

**Issue by MrVermond** [jbockle/format-files#9]
Hey there, 
first i would like to say thank you for the awesome extension. Its a pitty that an extension is required for such a standard feature but you really nailed it.

Sadly i discovered a problem what i think is a memory leak. It happens when i try to format my entire solution which have a lot of files (thousands). But the problem appears also a lot faster (hundred of files). 

Observing the memory consumption you can see how it goes up and never comes down again, so you have to restart VSCode and format files folder by folder which i bet is not the intention.

Do you have any idea what could cause the issue?

Im working with the latest official VSCode and the latest MS C++ plugin on a CentOs 7.

Best Regards
Nick

**Comment by jbockle** [comment]
I think its more likely the C++ plugin is having an issue, I'm not saying my code is perfect but it is fairly straightforward!  Due to the available APIs for vscode, my extension has to open each file, one file at a time, then I execute vscode's format and save command, then close the file.  I'll double check if there a api available to release resources in vscode, but my assumption is that vscode does this automatically when a file is closed.
